stages:
  - Linting
  - Test

test:
    stage: Test
    image: python:3.11.1
    before_script:
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install --upgrade pip
        - pip install -r requirements/test.txt
    script:
        - cd lyceum
        - python3 manage.py migrate
        - python3 manage.py test
    only:
        - main

flake8:
    stage: Linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements/prod.txt
        - pip install -r requirements/test.txt
    script:
        - flake8 --verbose .
    only:
        - main

black:
    stage: Linting
    image: registry.gitlab.com/pipeline-components/black:latest
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements/prod.txt
        - pip install -r requirements/test.txt
    script:
        - black --check --verbose -l 79 .
    only:
        - main