stages:
  - linting
  - build

install-dependencies:
    stage: .pre
    image: python:3.12.4
    script:
        - pip install -r requirements/test.txt

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements/test.txt
    script:
        - flake8 --verbose .
    only:
        - main

black-check:
    stage: linting
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
        - pip install --upgrade pip
        - pip install -r requirements/test.txt
        - black --check .
    only:
        - main
