stages:
  - linting

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements/prod.txt
    script:
        - flake8 --verbose .
    only:
        - main
