stages:
  - Linting
  - Test

test:
    stage: Test
    image: python:3.11.1
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements/test.txt
    script:
        - python manage.py migrate      
        - python -m unittest discover -s lyceum/homepage
        - python -m unittest discover -s lyceum/catalog
        - python -m unittest discover -s lyceum/about
    only:
        - main

flake8:
    stage: Linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements/prod.txt
        - pip install -r requirements/test.txt
    script:
        - flake8 --verbose .
    only:
        - main

black:
    stage: Linting
    image: registry.gitlab.com/pipeline-components/black:latest
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements/prod.txt
        - pip install -r requirements/test.txt
    script:
        - black --check --verbose -l 79 .
    only:
        - main