[tool.black]
line-length = 79
skip-string-normalization = false
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.flake8]
max-line-length = 79
plugins = [
    "flake8-naming"
    "flake8-isort"
    "flake8-quotes"
]

[tool.isort]
profile = black

[tool.flake8-quotes]
inline-quotes = "
multiline-quotes = "