# Generated by Django 4.2.16 on 2024-11-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя пользователя должно быть меньше 50 символов",
                        max_length=50,
                        verbose_name="имя",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Текст письма", verbose_name="текстовое поле"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время создания"
                    ),
                ),
                (
                    "mail",
                    models.EmailField(max_length=254, verbose_name="почта"),
                ),
            ],
        ),
    ]
