# Generated by Django 4.2.16 on 2024-11-11 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_feedback_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackfile",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="feedback.feedback",
            ),
        ),
    ]
