# Generated by Django 4.2.16 on 2024-11-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_alter_feedbackfile_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Сообщение обратной связи",
                "verbose_name_plural": "Сообщения обратной связи",
            },
        ),
        migrations.AlterModelOptions(
            name="feedbackauthor",
            options={"verbose_name": "Автор сообщения"},
        ),
        migrations.AlterModelOptions(
            name="feedbackfile",
            options={"verbose_name": "Файл", "verbose_name_plural": "Файлы"},
        ),
    ]
