# Generated by Django 4.2.16 on 2024-11-21 16:22

from django.db import migrations, models
import feedback.models
import lyceum.s3_storage


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0005_alter_feedback_options_alter_feedbackauthor_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackfile",
            name="file",
            field=models.FileField(
                blank=True,
                storage=lyceum.s3_storage.MediaStorage(),
                upload_to=feedback.models.FeedbackFile.get_path,
                verbose_name="файл",
            ),
        ),
    ]
