# Generated by Django 4.2.16 on 2024-11-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_statuslog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statuslog",
            options={
                "verbose_name": "Статус лог",
                "verbose_name_plural": "Статус логи",
            },
        ),
    ]
