# Generated by Django 4.2.16 on 2024-11-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_rename_from_status_statuslog_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="from",
            field=models.CharField(
                db_column="from", max_length=16, verbose_name="from"
            ),
        ),
        migrations.RenameField(
            model_name="statuslog",
            old_name="from",
            new_name="from_status",
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to",
            field=models.CharField(
                db_column="to", max_length=16, verbose_name="to"
            ),
        ),
        migrations.RenameField(
            model_name="statuslog",
            old_name="to",
            new_name="to_status",
        ),
    ]
