# Generated by Django 4.2.16 on 2024-11-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attempts_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="попыток входа"
            ),
        ),
    ]
