# Generated by Django 4.2.16 on 2024-11-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "профиль"},
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                blank=True, null=True, verbose_name="дата рождения"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="coffee_count",
            field=models.IntegerField(
                default=0, verbose_name="счетчик переходов по /coffee"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/profile_pics/",
                verbose_name="аватарка",
            ),
        ),
    ]
