# Generated by Django 4.2.16 on 2024-11-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_options_remove_profile_bio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Дополнительные поля"},
        ),
    ]
