# Generated by Django 4.2.16 on 2024-11-21 16:22

from django.db import migrations, models
import lyceum.s3_storage
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=lyceum.s3_storage.MediaStorage(),
                upload_to=users.models.Profile.image_path,
                verbose_name="изображение профиля",
            ),
        ),
    ]
