# Generated by Django 4.2.16 on 2024-11-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rating", "0001_initial"),
        (
            "users",
            "0002_user_alter_profile_options_profile_attempts_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to="users.user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "item")},
        ),
    ]
