# Generated by Django 4.2.16 on 2024-11-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0002_alter_rating_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Ненависть"),
                    (2, "Неприязнь"),
                    (3, "Нейтрально"),
                    (4, "Обожание"),
                    (5, "Любовь"),
                ],
                null=True,
            ),
        ),
    ]
