# Generated by Django 4.2.16 on 2024-11-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="время изменения оценки"
            ),
        ),
    ]
