# Generated by Django 4.2.16 on 2024-10-20 18:36

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="max 150 символов",
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(200)
                        ],
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=100,
                        help_text="Вес должен быть больше 0 и меньше 32768",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32768),
                        ],
                        verbose_name="Вес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="max 150 символов",
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Слаг содержит только латинские буквы, символы тире или нижнего подчеркиванияи цифры",
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(200)
                        ],
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="max 150 символов",
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        default="роскошно превосходно",
                        help_text="Описание должно содержать строку, содержащую в себе `превосходно` или `роскошно` ",
                        validators=[catalog.validators.custom_validator],
                        verbose_name="Описание",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_items",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="catalog_items", to="catalog.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
