# Generated by Django 4.2.16 on 2024-10-21 17:16

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Описание должно содержать слова 'превосходно' или 'роскошно'",
                validators=[catalog.validators.custom_validator],
                verbose_name="описание",
            ),
        ),
    ]
