# Generated by Django 4.2.16 on 2024-10-18 22:00

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("is_published", models.BooleanField(default=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("is_published", models.BooleanField(default=True)),
                ("slug", models.SlugField(unique=True)),
                ("weight", models.IntegerField(default=100)),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AddField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="text",
            field=models.TextField(
                default="роскошно превосходно",
                help_text="Описание должно содержать строку, содержащую в себе `превосходно` или `роскошно` ",
                validators=[catalog.models.custom_validator],
                verbose_name="Описание",
            ),
        ),
    ]
