# Generated by Django 4.2.16 on 2024-10-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0002_category_canonical_name_tag_canonical_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainimage",
            options={
                "verbose_name": "картинка",
                "verbose_name_plural": "картинки",
            },
        ),
    ]
