# Generated by Django 4.2.16 on 2024-10-19 19:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0002_category_tag_alter_item_options_item_is_published_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_items",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                related_name="catalog_items", to="catalog.tag"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(
                help_text="max 150 символов",
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(
                help_text="max 150 символов",
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.TextField(
                help_text="max 150 символов",
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Название",
            ),
        ),
    ]
