# Generated by Django 4.2.16 on 2024-10-19 20:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0003_item_category_item_tags_alter_category_is_published_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="weight",
        ),
        migrations.AddField(
            model_name="category",
            name="weight",
            field=models.IntegerField(
                default=100,
                help_text="Вес должен быть больше 0 и меньше 32768",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32768),
                ],
                verbose_name="Вес",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_items",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Слаг содержит только латинские буквы, символы тире или нижнего подчеркиванияи цифры",
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="Слаг",
            ),
        ),
    ]
