# Generated by Django 4.2.16 on 2024-10-30 23:39

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_image_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "фото", "verbose_name_plural": "фото"},
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor.fields.RichTextField(
                help_text="Описание должно содержать слова 'превосходно' или 'роскошно'",
                validators=[
                    catalog.validators.WordsValidator(
                        "роскошно", "превосходно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
    ]
