# Generated by Django 4.2.16 on 2024-11-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_item_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "default_related_name": "items",
                "ordering": ("is_published",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False, verbose_name="на главной странице"
            ),
        ),
    ]
