# Generated by Django 4.2.16 on 2024-11-20 19:54

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_merge_20241120_2254"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "default_related_name": "items",
                "ordering": ("-is_published",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="время создания"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False, verbose_name="на главной странице"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="время изменения"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Описание должно содержать слова 'превосходно' или 'роскошно'",
                validators=[
                    catalog.validators.WordsValidator(
                        "роскошно", "превосходно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
    ]
