# Generated by Django 4.2.16 on 2024-11-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_item_options_item_is_on_main"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "default_related_name": "items",
                "ordering": ("-is_published",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
