# Generated by Django 4.2.16 on 2024-11-04 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_item_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="время создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="время изменения"
            ),
        ),
    ]
