# Generated by Django 4.2.16 on 2024-11-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0007_alter_image_item_alter_item_category_alter_item_tags",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=100000.0,
                help_text="Укажите стоимость товара в рублях",
                max_digits=9,
                verbose_name="цена",
            ),
        ),
    ]
