# Generated by Django 4.2.16 on 2024-11-07 22:57

from django.db import migrations, models
import lyceum.s3_storage


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_item_created_item_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default=None,
                storage=lyceum.s3_storage.MediaStorage(),
                upload_to="catalog/",
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(
                default=None,
                storage=lyceum.s3_storage.MediaStorage(),
                upload_to="catalog/",
                verbose_name="изображение",
            ),
        ),
    ]
