# Generated by Django 4.2.16 on 2024-11-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default=None, upload_to="catalog/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(
                default=None, upload_to="catalog/", verbose_name="изображение"
            ),
        ),
    ]
