# Generated by Django 4.2.16 on 2024-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_image_image_alter_mainimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="время создания"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="время изменения"
            ),
        ),
    ]
