# Generated by Django 4.2.16 on 2024-11-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0002_alter_item_options_category_canonical_name_and_more",
        ),
        ("catalog", "0011_alter_item_created_alter_item_updated"),
    ]

    operations = []
