# Generated by Django 4.2.16 on 2024-11-20 18:54

import catalog.validators
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_item_created_alter_item_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Описание должно содержать слова 'превосходно' или 'роскошно'",
                validators=[
                    catalog.validators.WordsValidator(
                        "роскошно", "превосходно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
    ]
