# Generated by Django 4.2.16 on 2024-11-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="количество"
            ),
        ),
    ]
