# Generated by Django 4.2.16 on 2024-11-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_item_price"),
        ("cart", "0002_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "item")},
        ),
    ]
