# Generated by Django 4.2.16 on 2024-12-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="added",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="время добавления"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="items",
                to="cart.cart",
            ),
        ),
    ]
