# Generated by Django 4.2.16 on 2024-11-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="full_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="стоимость"
            ),
        ),
    ]
