# Generated by Django 4.2.16 on 2024-12-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cartitem_added_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ("-added",),
                "verbose_name": "Товар корзины",
                "verbose_name_plural": "Товары корзины",
            },
        ),
    ]
