name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black -r requirements/dev.txt

      - name: Run flake8
        run: flake8 .

      - name: Run black (check mode)
        run: black --check .

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements/test.txt

      - name: Migrate database
        run: python lyceum/manage.py migrate

      - name: Run Django tests
        run: python lyceum/manage.py test